const llantas = [
    {   id: 1,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 2,
        name: "product 2",
        price: "price 2",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 3,
        name: "product 3",
        price: "price 3",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 4,
        name: "product 4",
        price: "price 4",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 5,
        name: "product 5",
        price: "price 5",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 6,
        name: "product 6",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 7,
        name: "product 7",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
]

const sistemaArrastre = [
    {
        id: "1",	
        name: " LUBRICANTE SECO DRY ",
        mark: " FINISH LINE ",
        price: "38",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E1.jpg",
    },
    {
        id: "2",	
        name: " LUBRICANTE HUMEDO WET ",
        mark: " FINISH LINE ",
        price: "27",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E2.jpg",
    },
    {
        id: "3",	
        name: " LUBRICANTE CERA CERAMICO ",
        mark: " FINISH LINE ",
        price: "42",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E3.jpg",
    },
    {
        id: "4",	
        name: " DESENGRASANTE SPEED ",
        mark: " FINISH LINE ",
        price: "49",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E4.jpg",
    },
    {
        id: "5",	
        name: " LUBRICANTE + APLICADOR ",
        mark: " FINISH LINE ",
        price: "69",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E5.jpg",
    },
    {
        id: "6",	
        name: "DISCO DE FRENO CRF230 - TORNADO",
        mark: "DMT RACING",
        price: "178",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E6.jpg",
    },
    
    {
        id: "7",	
        name: "PIÑON 13D CRF230",
        mark: "RENTHAL",
        price: "129",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E7.jpg",
    },
    {
        id: "8",	
        name: "CANEDILLA DE DISTRIBUCION DID CRF230",
        mark: "DID ",
        price: "97",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E8.jpg",
    },
    {
        id: "9",	
        name: "KIT DE ARRASTRE PULSAR NS 200",
        mark: "SFX",
        price: "129",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E9.jpg",
    },
    {
        id: "10",	
        name: "KIT DE ARRATRE O-RING CRF 230",
        mark: "SFX",
        price: "139",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E10.jpg",
    },
    {
        id: "11",	
        name: "CATALINA ALUMINIO",
        mark: "KIGCOL",
        price: "189",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E11.jpg",
    },
    {
        id: "12",	
        name: "ZAPATA DE FRENO CRF230 ",
        mark: "FERODO",
        price: "39",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E12.jpg",
    },
    {
        id: "13",	
        name: "ZAPATA DE FRENO CRF230 ",
        mark: "KIGCOL",
        price: "25",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E13.jpg",
    },
    {
        id: "14",	
        name: "KIT DE ARRASTRE YAMAHA FZ16",
        mark: "SFX",
        price: "96",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E14.jpg",
    },
    {
        id: "15",	
        name: "KIT DE ARRASTRE HONDA XL 200",
        mark: "SFX",
        price: "78",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E15.jpg",
    },
    {
        id: "16",	
        name: "CATALINA ALUMINIO",
        mark: "RENTHAL",
        price: "338",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E16.jpg",
    },
    {
        id: "17",	
        name: "KIT DE ARRASTRE YAMAHA XTZ 125",
        mark: "SFX",
        price: "98",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E17.jpg",
    },
    {
        id: "19",	
        name: "KIT DE ARRASTRE YAMAHA R 15",
        mark: "SFX",
        price: "97",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E19.jpg",
    },
    {
        id: "20",	
        name: "KIT DE ARRASTRE PULSAR 180 UG4",
        mark: "SFX",
        price: "98",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E20.jpg",
    },
    {
        id: "21",	
        name: "KIT DE ARRASTRE HONDA BROSS XR 125",
        mark: "SFX",
        price: "98",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E21.jpg",
    },
    {
        id: "23",	
        name: "KIT DE ARRASTRE HONDA CRF 230",
        mark: "SFX",
        price: "139",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E23.jpg",
    },
    {
        id: "24",	
        name: "KIT DE ARRASTRE HONDA CB 190R",
        mark: "CHOHO",
        price: "98",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E24.jpg",
    },
    {
        id: "25",	
        name: "KIT DE ARRASTRE HONDA TORNADO 250",
        mark: "SFX",
        price: "129",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E25.jpg",
    },
    {
        id: "26",	
        name: "KIT DE ARRASTRE PULSAR 220",
        mark: "SFX",
        price: "129",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E26.jpg",
    },
    {
        id: "28",	
        name: "KIT DE ARRASTRE HONDA CRB 250",
        mark: "CHOHO",
        price: "97",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E28.jpg",
    },
    {
        id: "29",	
        name: "KIT DE ARRASTRE YAMAHA YZF- R15",
        mark: "CHOHO",
        price: "96",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E29.jpg",
    },
    {
        id: "30",	
        name: "KIT DE ARRASTRE KTM DUKE 200",
        mark: "CHOHO",
        price: "129",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaArrastre/E30.jpg",
    },
    
  
    
]

const sistemaElectrico = [
    {
        id: "1",	
        name: "CDI SIN LIMITADOR CRF 230F",
        mark: "SERVITEC",
        price: "198",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaElectrico/H1.jpg",
    },
    {
        id: "2",	
        name: "CDI SIN LIMITADOR CRF 230F",
        mark: "MAGNETRON",
        price: "228",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaElectrico/H2.jpg",
    },
    
    {
        id:"3",	
        name: "BOBINA ENCENDIDO CRF 230",
        mark: "MAGNETRON",
        price: "149",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaElectrico/H3.jpg",
    },
    {
        id: "4",	
        name: "BUGIA IRIDIUM NGK (JAPONES DPR8EIX)",
        mark: "NGK",
        price: "37",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaElectrico/H4.jpg",
    },
    {
        id: "5",	
        name: "FARO CON MASCARA CRF 230F",
        mark: "",
        price: "78",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaElectrico/H5.jpg",
    },
    {
        id: "6",	
        name: "CANCHITO ARRANCADOR CRF 230F",
        mark: "",
        price: "29",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/sistemaElectrico/H6.jpg",
    },
    
    
]

const sistemaMotor = [
    {   id: 1,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 2,
        name: "product 2",
        price: "price 2",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 3,
        name: "product 3",
        price: "price 3",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 4,
        name: "product 4",
        price: "price 4",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 5,
        name: "product 5",
        price: "price 5",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 6,
        name: "product 6",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 7,
        name: "product 7",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
]

const luces = [
    {   id: 1,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 2,
        name: "product 2",
        price: "price 2",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 3,
        name: "product 3",
        price: "price 3",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 4,
        name: "product 4",
        price: "price 4",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 5,
        name: "product 5",
        price: "price 5",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 6,
        name: "product 6",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 7,
        name: "product 7",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
]

const accesoriosMotor = [
    {
        id: "1",	
        name: "PORTA ALFORJAS ",
        mark: "LEOS PARTS",
        price: "210",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosMotor/A1.jpg",
    },
    {
        id: "2",	
        name: "SLIDER",
        mark: "LEOS PARTS",
        price: "149",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosMotor/A2.jpg",
    },
    {
        id: "3",	
        name: "PARRILLA ",
        mark: "LEOS PARTS",
        price: "138",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosMotor/A3.jpg",
    },
    {
        id: "4",	
        name: "PROTE RADEADOR",
        mark: "LEOS PARTS",
        price: "149",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosMotor/A4.jpg",
    },
    {
        id: "1",	
        name: "PORTA ALFORJAS ",
        mark: "LEOS PARTS",
        price: "210",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosMotor/A1.jpg",
    },
    {
        id: "2",	
        name: "SLIDER",
        mark: "LEOS PARTS",
        price: "149",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosMotor/A2.jpg",
    },
    {
        id: "3",	
        name: "PARRILLA ",
        mark: "LEOS PARTS",
        price: "138",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosMotor/A3.jpg",
    },
    
    
]

const accesoriosPiloto = [
    {
        id: "1",	
        name: "TRAJE 180 TRICE (GREY ORANGE)",
        mark: "FOX",
        price: "667",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C1.jpg",
    },
    {
        id: "2",	
        name: "TRAJE 180 TRICE (TEAL)",
        mark: "FOX",
        price: "667",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C2.jpg"

    },
    {
        id: "3",	
        name: "TRAJE 180 LUX (BLACK WHITE)",
        mark: "FOX",
        price: "538",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C3.jpg"

    }
    ,
    {
        id: "4",	
        name: "TRAJE 180 LUX (BLACK BLACK)",
        mark: "FOX",
        price: "538",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C4.jpg"

    },
    {
        id: "5",	
        name: "TRAJE 180 SKEW (BLACK)",
        mark: "FOX",
        price: "658",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C5.jpg"

    },
    {   id:"6",   
        name: "TRAJE 180 PRIX (BLUE)",
        mark: "FOX",
        price: "568",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C6.jpg"
    },

    {   id:"7",   
        name: "TRAJE 180 MASTAR (YELLOW)",
        mark: "FOX",
        price: "448",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C7.jpg"
    },
        
    {   id:"8",   
        name: "TRAJE 180 VICIOS (BLUE PINK)",
        mark: "FOX",
        price: "448",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C8.jpg"
    },

    {   id:"9",   
        name: "TRAJE FACTORY EDITION (NEGRO ROSA)",
        mark: "PRO TORK",
        price: "278",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C9.jpg"
    },

    {   id:"10",   
        name: "TRAJE FACTORY EDITION (NEGRO ROSA)",
        mark: "PRO TORK",
        price: "298",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C10.jpg"
    },
    
    {   id: "11",   
        name: "BOTAS COMP BOOT (BLACK YELLOW)",
        mark: "FOX",
        price: "1057",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C11.jpg"
    },
    {   id: "12",   
        name: "BOTAS INSTINCT ARTICULABLES (BLACK)",
        mark: "FOX",
        price: "2149",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C12.jpg"
    },
    {   id: "13",   
        name: "BOTAS COMP BOOT (BLACK)",
        mark: "FOX",
        price: "989",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C12.jpg"
    },
    {   id: "14",   
        name: "BOTAS COMP X BOOT (BLACK)",
        mark: "FOX",
        price: "1079",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C13.jpg"
    },

    {   id: "15",   
        name: "BOTAS INSTINCT ARTICULABLES (GREY RED)",
        mark: "FOX",
        price: "1889",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C15.jpg"
    },
    
    {   id: "16",   
        name: "BOTAS INSTINCT ARTICULABLES (BLACK)",
        mark: "FOX",
        price: "1889",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C16.jpg"
    },

     
    {   id: "17",   
        name: "BOTAS BOOT 3.5 (BLACK RED)",
        mark: "LEATIA",
        price: "897",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C17.jpg"
    },
        
    {   id: "18",   
        name: "BOTAS X ROCK (BLACK SILVER)",
        mark: "ACERBID",
        price: "1379",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C18.jpg"
    },
    {   id: "19",   
        name: "BOTAS X ROCK (BLACK)",
        mark: "ACERBID",
        price: "1379",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C19.jpg"
    },

    {   id: "20",   
        name: "CASCO FAST EVO (BLACK MX 437)",
        mark: "LS2",
        price: "439",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C20.jpg"
    },
    {   id: "21",   
        name: "CASCO SUBVERTER (RASCAL MX 700)",
        mark: "LS2",
        price: "649",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C21.jpg"
    },

    {   id: "22",   
        name: "CASCO FAST EVO (TOWFER MX 437)",
        mark: "LS2",
        price: "439",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C22.jpg"
    },

    {   id: "23",   
        name: "CASCO SUBVERTER (TROOP MX 700)",
        mark: "LS2",
        price: "649",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C23.jpg"
    },

    {   id: "24",   
        name: "CASCO SUBVERTER (SINGLEMONO MX 700)",
        mark: "LS2",
        price: "649",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C24.jpg"
    },

    {   id: "25",   
        name: "CASCO VOLT MX 437",
        mark: "LS2",
        price: "458",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C25.jpg"
    },
      
    {   id: "26",   
        name: "CASCO TWIST FREEDOM (YELLOW GLOSS)",
        mark: "AIROH",
        price: "598",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C26.jpg"
    }, 

    {   id: "27",   
        name: "CASCO TWIST MIX (ORANGE GLOSS)",
        mark: "AIROH",
        price: "598",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C27.jpg"
    }, 
    {   id: "28",   
        name: "CASCO SX-1 SONIC (BLACK YELLOW)",
        mark: "BELL",
        price: "359",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C28.jpg"
    }, 
    {   id: "29",   
        name: "CASCO PG 3095 (YELLOW FLUO)",
        mark: "PROGRIP",
        price: "439",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C29.jpg"
    }, 
      
    {   id: "30",   
        name: "CASCO FACTORY EDITION (BLUE SKY)",
        mark: "PRO TORK",
        price: "247",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C30.jpg"
    },
    {   id: "31",   
        name: "CASCO FACTORY EDITION (YELLOW BLUE)",
        mark: "PRO TORK",
        price: "247",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C31.jpg"
    },
    {   id: "32",   
        name: "CASCO FACTORY EDITION (YELLOW NEON)",
        mark: "PRO TORK",
        price: "247",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C32.jpg"
    },  
    {   id: "33",   
        name: "CASCO + GOGGLES (YELLOW BLUE)",
        mark: "SOMAN",
        price: "348",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C33.jpg"
    },
    {   id: "34",   
        name: "CASCO + GOGGLES (RED BLACK)",
        mark: "SOMAN",
        price: "348",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C34.jpg"
    },
    {   id: "35",   
        name: "BOLSA CAMEL BAG 2.5L ",
        mark: "ACERBID",
        price: "253",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C35.jpg"
    },    
    {   id: "36",   
        name: "BOLSA CAMEL BAG 2.0L ",
        mark: "ACERBID",
        price: "268",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C36.jpg"
    },
    {   id: "37",   
        name: "PECHERA (BLANCO)",
        mark: "ACERBID",
        price: "329",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C37.jpg"
    },
    {   id: "38",   
        name: "PECHERA (NEGRO)",
        mark: "ACERBID",
        price: "329",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C38.jpg"
    },

    {   id: "39",   
        name: "PECHERA (AZUL)",
        mark: "ACERBID",
        price: "329",
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/racingwc/src/assets/static/products/accesoriosPilotos/C38.jpg"
    },
]

const sistemaFrenos = [
    {   id: 1,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 2,
        name: "product 2",
        price: "price 2",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 3,
        name: "product 3",
        price: "price 3",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 4,
        name: "product 4",
        price: "price 4",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 5,
        name: "product 5",
        price: "price 5",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 6,
        name: "product 6",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 7,
        name: "product 7",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
]

export {
    llantas, 
    sistemaArrastre,
    sistemaElectrico,
    sistemaMotor,
    luces,
    accesoriosMotor, 
    accesoriosPiloto,
    sistemaFrenos
};