const llantas = [
    {   id: 1,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t1.jpeg",
    },
    {   id: 2,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t2.jpeg",
    },
    {   id: 3,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t3.jpeg",
    },
    {   id: 4,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t4.jpeg",
    },
    {   id: 5,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t5.jpeg",
    },
    {   id: 6,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t6.jpeg",
    },
    {   id: 7,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t7.jpeg",
    },
    {   id: 8,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t8.jpeg",
    },
    {   id: 9,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t8.jpeg",
    },
    {   id: 10,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t9.jpeg",
    },
    {   id: 11,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t10.jpeg",
    },
    {   id: 12,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t11.jpeg",
    },
    {   id: 13,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t12.jpeg",
    },
    {   id: 14,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t13.jpeg",
    },
    {   id: 15,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t14.jpeg",
    },
    {   id: 16,
        image: "https://raw.githubusercontent.com/addleonel/trees/main/src/assets/static/products/t15.jpeg",
    },
]

export {
    llantas
};